# .travis.yml
dist: trusty
sudo: required

install:
 - wget -O /tmp/hugo.deb https://github.com/spf13/hugo/releases/download/v0.26/hugo_0.26_Linux-64bit.deb
 - sudo dpkg -i /tmp/hugo.deb

script:
 - hugo

deploy:
  provider: surge
  project: ./public/
  domain: https://cipri-redesign.surge.sh
  skip_cleanup: true
  on:
    all_branches: true